### PR TITLE
Update resetPassword.email.js

### PR DESCRIPTION
**Pull request by Marthacz**

### CODE REVIEW

**Comment by Marthacz** [comment]
Same as other email template: We need to add Thanks, AI Global Team with a space? How would that work?

**Review by sshh12 — APPROVED** [review]

**Comment by sshh12** [comment]
@Marthacz several options:
* (for text) https://stackoverflow.com/questions/805107/creating-multiline-strings-in-javascript
* (for text) You can use \n
* (for HTML) You can use <br/>

**Comment by Marthacz** [comment]
What is it for HTML?

**Comment by sshh12** [comment]
lol it hid it `<br/>`

**Pull request merged**
